# Generated by Django 6.0 on 2025-12-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('enlace', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='proyectos/')),
            ],
        ),
    ]
