# Generated by Django 6.0 on 2025-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_proyecto_updated_alter_proyecto_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
